server.port=9020

# Database (same as ws-security)
spring.datasource.url=jdbc:postgresql://localhost:5432/i12logosdb
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:Yeshua12}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# CORS
security.cors.allowed-origins=http://localhost:5173,http://localhost:5174,http://localhost:4200

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# PagBank Sandbox
pagbank.subscriptions.url=https://sandbox.api.assinaturas.pagseguro.com
pagbank.orders.url=https://sandbox.api.pagseguro.com
pagbank.token=b9ef5beb-732a-42f2-b1ad-22feb4f7a9c728aa1a19452f80f03e611db561415b296342-4d8e-47f5-acff-669297dcedcd

# ws-security internal
api.security.url=http://localhost:8080

# SendGrid (dev - key configured via env or here)
sendgrid.api.key=${SENDGRID_API_KEY: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}

# Feign Logging
logging.level.br.eti.logos.feign=DEBUG
feign.client.config.default.loggerLevel=FULL
