server.address=0.0.0.0
app.env=prd
server.port=8090

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
server.error.include-stacktrace=never

security.cors.allowed-origins=${SECURITY_CORS_ALLOWED_ORIGINS}

spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

pagbank.subscriptions.url=https://api.assinaturas.pagseguro.com
pagbank.orders.url=https://api.pagseguro.com
pagbank.token=${PAGBANK_TOKEN}
pagbank.webhook.url=${PAGBANK_WEBHOOK_URL}

api.security.url=${API_SECURITY_URL}

# Email (Amazon SES via SMTP)
spring.mail.username=${SES_SMTP_USERNAME}
spring.mail.password=${SES_SMTP_PASSWORD}

email.from=${EMAIL_FROM:naoresponda@logos.eti.br}
email.from.name=${EMAIL_FROM_NAME:i12}
