package br.eti.logos.enums;

public enum WebhookEventTypeEnum {
    SUBSCRIPTION_CREATED,
    SUBSCRIPTION_ACTIVATED,
    SUBSCRIPTION_SUSPENDED,
    SUBSCRIPTION_CANCELED,
    INVOICE_CREATED,
    INVOICE_PAID,
    INVOICE_OVERDUE,
    INVOICE_CANCELED,
    INVOICE_REFUNDED
}
